---
jobs:
- name: build-deploy
  public: true
  serial: true
  plan:
  - get: hellocloud
    trigger: true
  - task: build-hellocloud
    config:
      platform: linux
      image: docker:///stuartblair/javabuild
      inputs:
        - name: hellocloud
      run:
        path: ./hellocloud/ci
  - put: deployment
    params:
      manifest: hellocloud/manifest.yml
      path: ../put/build-hellocloud/hellocloud/build/libs/hellocloud-0.0.1-SNAPSHOT.jar

resources:
- name: hellocloud
  type: git
  source:
    uri: http://github.gapinc.dev/St752kx/hellocloud.git
    private_key: {{hellocloud-github-private-key}}

- name: deployment
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
